// File generated by FlutterFire CLI — buscapet-57193
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) return web;
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        return web;
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCW0_3ZsVOdjr_94CkbZVVBLA9s--8QT4c',
    authDomain: 'buscapet-57193.firebaseapp.com',
    projectId: 'buscapet-57193',
    storageBucket: 'buscapet-57193.firebasestorage.app',
    messagingSenderId: '694866246233',
    appId: '1:694866246233:web:97e000138a44d77a574f48',
  );

  // NOTA: Para Android e iOS necesitás registrar la app en Firebase Console
  // y descargar google-services.json (Android) y GoogleService-Info.plist (iOS)
  // Por ahora usamos la config web como fallback
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEb7kd09fZOh7AJmnumZuqqj9k2d4-mAY',
    appId: '1:694866246233:android:037edd315e9b6c36574f48',
    messagingSenderId: '694866246233',
    projectId: 'buscapet-57193',
    storageBucket: 'buscapet-57193.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCW0_3ZsVOdjr_94CkbZVVBLA9s--8QT4c',
    authDomain: 'buscapet-57193.firebaseapp.com',
    projectId: 'buscapet-57193',
    storageBucket: 'buscapet-57193.firebasestorage.app',
    messagingSenderId: '694866246233',
    appId: '1:694866246233:web:97e000138a44d77a574f48',
    iosBundleId: 'com.buscapet.app',
  );
}
